In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd

In [2]:
# Cargar el DataFrame generado previamente
# Asegúrate de que el DataFrame tenga columnas ['x', 'y', 'z'] y ['interpolated_valor1', ..., 'interpolated_valor200']
df = pd.read_csv('interpolated_results.csv')

In [3]:
# Separar las características (X) y las etiquetas (y)
X = df[['x', 'y', 'z']].values  # Coordenadas (entradas)
y = df.iloc[:, 3:].values       # Energías (salidas)

In [4]:
# Dividir los datos en entrenamiento y prueba (80%-20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Escalar las características para mejorar el rendimiento del modelo
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
from sklearn.linear_model import Ridge  # Cambia esto a Lasso si prefieres Lasso

In [7]:
# Entrenar el modelo de regresión con regularización Ridge (puedes cambiarlo a Lasso si prefieres)
model = Ridge(alpha=1.0)  # 'alpha' controla la regularización
model.fit(X_train_scaled, y_train)

Ridge()

In [8]:
# Realizar predicciones
y_pred = model.predict(X_test_scaled)

In [9]:
# Evaluar el modelo
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Modelo de regresión lineal con Ridge:")
print(f" - MSE: {mse:.4f}")
print(f" - R²: {r2:.4f}")
print("-------------------------------")

Modelo de regresión lineal con Ridge:
 - MSE: 0.0002
 - R²: 0.7396
-------------------------------


In [10]:
# Si deseas guardar el modelo entrenado
import pickle
with open('modelo_regresion_lineal.pkl', 'wb') as f:
    pickle.dump(model, f)

In [11]:
# También puedes guardar las predicciones
predictions_df = pd.DataFrame(y_pred, columns=[f'pred_valor{i+1}' for i in range(y_pred.shape[1])])
predictions_df.to_csv('predicciones.csv', index=False)


In [12]:
import numpy as np

# Definir los límites del cubo con los valores mínimo y máximo de las coordenadas x, y, z
x_min, x_max = df['x'].min(), df['x'].max()
y_min, y_max = df['y'].min(), df['y'].max()
z_min, z_max = df['z'].min(), df['z'].max()

# Generar coordenadas aleatorias dentro de los límites del cubo
num_samples = 5  # Número de coordenadas aleatorias que quieres generar
random_coordinates = np.array([
    [np.random.uniform(x_min, x_max), 
     np.random.uniform(y_min, y_max), 
     np.random.uniform(z_min, z_max)]
    for _ in range(num_samples)
])

In [13]:
print(random_coordinates)

[[ 0.57819406  0.03395883 -0.80383056]
 [ 0.6059717   0.48034312  0.62059065]
 [ 0.05799898 -0.03723788  0.28382013]
 [ 0.80157249 -0.42799389  0.23585044]
 [ 0.26349286 -0.247986    0.8674509 ]]


In [14]:
# Predicción de la energía para las coordenadas aleatorias
predicted_energies = model.predict(random_coordinates)

print(predicted_energies)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.00655965 0.05984166 0.08839496 0.0743063  0.08195769
  0.07217397 0.14311683 0.16649135 0.132279   0.15549027 0.1636196
  0.10662734 0.10761111 0.10533603 0.1008431  0.09323214 0.10834428
  0.10349284 0.06968297 0.10778433 0.09822401 0.07125679 0.06998157
  0.06809503 0.05527541 0.05685994 0.07020881 0.06488507 0.0662307
  0.06895069 0.06286248 0.06425773 0.05288603 0.05263285 0.05410644
  0.05176479 0.04294181 0.04731144 0.04553845 0.04329077 0.0402882
  0.03722985 0.04268854 0.03992942 0.03840597 0.03571068 0.03447595
  0.03140098 0.030082   0.03144594 0.02983241 0.02844158 0.02826071
  0.02996383 0.02769726 0.02595089 0.02566357 0.02333886 0.02350212
  0.02220654 0.02049811 0.02260214 0.01962471 0.01906189 0.01910232
  0.01720217 0.016475   0.01635422 0.01618594 0.01461891 0.01415043
  0.01359961 0.01321706 0.01379671 0.01142253 0.01196    0.01348493

In [19]:
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# 1. Cargar el archivo de predicciones
df_pred = pd.read_csv("predicciones.csv")

In [20]:
df_pred

pred_valor1  pred_valor2  pred_valor3  pred_valor4  pred_valor5  \
0             0.0          0.0          0.0          0.0          0.0   
1             0.0          0.0          0.0          0.0          0.0   
2             0.0          0.0          0.0          0.0          0.0   
3             0.0          0.0          0.0          0.0          0.0   
4             0.0          0.0          0.0          0.0          0.0   
...           ...          ...          ...          ...          ...   
9995          0.0          0.0          0.0          0.0          0.0   
9996          0.0          0.0          0.0          0.0          0.0   
9997          0.0          0.0          0.0          0.0          0.0   
9998          0.0          0.0          0.0          0.0          0.0   
9999          0.0          0.0          0.0          0.0          0.0   

      pred_valor6  pred_valor7  pred_valor8  pred_valor9  pred_valor10  ...  \
0             0.0          0.0          0.0          0.0           0.0  ...   
1             0.0          0.0          0.0          0.0           0.0  ...   
2             0.0          0.0          0.0          0.0           0.0  ...   
3             0.0          0.0          0.0          0.0           0.0  ...   
4             0.0          0.0          0.0          0.0           0.0  ...   
...           ...          ...          ...          ...           ...  ...   
9995          0.0          0.0          0.0          0.0           0.0  ...   
9996          0.0          0.0          0.0          0.0           0.0  ...   
9997          0.0          0.0          0.0          0.0           0.0  ...   
9998          0.0          0.0          0.0          0.0           0.0  ...   
9999          0.0          0.0          0.0          0.0           0.0  ...   

      pred_valor191  pred_valor192  pred_valor193  pred_valor194  \
0          0.000367       0.000356       0.000345       0.000334   
1          0.000366       0.000355       0.000344       0.000333   
2          0.000347       0.000336       0.000326       0.000315   
3          0.000371       0.000359       0.000348       0.000337   
4          0.000358       0.000346       0.000336       0.000325   
...             ...            ...            ...            ...   
9995       0.000370       0.000359       0.000348       0.000337   
9996       0.000365       0.000354       0.000343       0.000332   
9997       0.000345       0.000334       0.000324       0.000314   
9998       0.000379       0.000368       0.000356       0.000345   
9999       0.000372       0.000361       0.000350       0.000339   

      pred_valor195  pred_valor196  pred_valor197  pred_valor198  \
0          0.000324       0.000314       0.000304       0.000294   
1          0.000323       0.000313       0.000303       0.000294   
2          0.000306       0.000296       0.000287       0.000278   
3          0.000327       0.000317       0.000307       0.000297   
4          0.000315       0.000305       0.000296       0.000287   
...             ...            ...            ...            ...   
9995       0.000326       0.000316       0.000306       0.000297   
9996       0.000322       0.000312       0.000302       0.000293   
9997       0.000304       0.000294       0.000285       0.000276   
9998       0.000334       0.000324       0.000314       0.000304   
9999       0.000328       0.000318       0.000308       0.000299   

      pred_valor199  pred_valor200  
0          0.000285       0.000276  
1          0.000285       0.000276  
2          0.000269       0.000261  
3          0.000288       0.000279  
4          0.000278       0.000269  
...             ...            ...  
9995       0.000288       0.000279  
9996       0.000283       0.000275  
9997       0.000268       0.000260  
9998       0.000295       0.000286  
9999       0.000289       0.000280  

[10000 rows x 200 columns]