In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd

In [2]:
# Cargar el DataFrame generado previamente
# Asegúrate de que el DataFrame tenga columnas ['x', 'y', 'z'] y ['interpolated_valor1', ..., 'interpolated_valor200']
df = pd.read_csv('interpolated_results.csv')

In [3]:
# Separar las características (X) y las etiquetas (y)
X = df[['x', 'y', 'z']].values  # Coordenadas (entradas)
y = df.iloc[:, 3:].values       # Energías (salidas)

In [4]:
# Dividir los datos en entrenamiento y prueba (80%-20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
# Escalar las características para mejorar el rendimiento del modelo
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
from sklearn.linear_model import Ridge  # Cambia esto a Lasso si prefieres Lasso

In [7]:
# Entrenar el modelo de regresión con regularización Ridge (puedes cambiarlo a Lasso si prefieres)
model = Ridge(alpha=1.0)  # 'alpha' controla la regularización
model.fit(X_train_scaled, y_train)

Ridge()

In [8]:
# Realizar predicciones
y_pred = model.predict(X_test_scaled)

In [9]:
# Evaluar el modelo
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Modelo de regresión lineal con Ridge:")
print(f" - MSE: {mse:.4f}")
print(f" - R²: {r2:.4f}")
print("-------------------------------")

Modelo de regresión lineal con Ridge:
 - MSE: 0.0002
 - R²: 0.7396
-------------------------------


In [10]:
# Si deseas guardar el modelo entrenado
import pickle
with open('modelo_regresion_lineal.pkl', 'wb') as f:
    pickle.dump(model, f)

In [11]:
# También puedes guardar las predicciones
predictions_df = pd.DataFrame(y_pred, columns=[f'pred_valor{i+1}' for i in range(y_pred.shape[1])])
predictions_df.to_csv('predicciones.csv', index=False)


In [12]:
import numpy as np

# Definir los límites del cubo con los valores mínimo y máximo de las coordenadas x, y, z
x_min, x_max = df['x'].min(), df['x'].max()
y_min, y_max = df['y'].min(), df['y'].max()
z_min, z_max = df['z'].min(), df['z'].max()

# Generar coordenadas aleatorias dentro de los límites del cubo
num_samples = 5  # Número de coordenadas aleatorias que quieres generar
random_coordinates = np.array([
    [np.random.uniform(x_min, x_max), 
     np.random.uniform(y_min, y_max), 
     np.random.uniform(z_min, z_max)]
    for _ in range(num_samples)
])

In [13]:
print(random_coordinates)

[[-0.66560263 -0.77146525 -0.46478275]
 [-0.75599631  0.52079949 -0.52783388]
 [ 0.14213229  0.05970361 -0.85366919]
 [ 0.63608624 -0.24697159  0.12428977]
 [ 0.60017993  0.70276758 -0.4590251 ]]


In [14]:
# Predicción de la energía para las coordenadas aleatorias
predicted_energies = model.predict(random_coordinates)

print(predicted_energies)

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.00289315  0.0095426  -0.02042184 -0.00210653  0.0013834
   0.01942074  0.06465769  0.07873963  0.07372612  0.13032648  0.15891133
   0.12229433  0.14242053  0.13761633  0.13119056  0.11539324  0.12305216
   0.11075813  0.06576817  0.09804698  0.10763599  0.08051621  0.07227494
   0.07429242  0.05318294  0.04405798  0.05741402  0.05384195  0.06242677
   0.06379668  0.05858698  0.07310023  0.05357379  0.05481353  0.04996526
   0.05747206  0.04651947  0.04551005  0.04595845  0.04524732  0.04135406
   0.03898954  0.04591368  0.03930888  0.03993406  0.03596219  0.03135469
   0.02991628  0.02856628  0.02711285  0.02742794  0.0266179   0.02858644
   0.03002163  0.02645741  0.02629447  0.02592834  0.02253218  0.02305074
   0.02297619  0.0206678   0.02376643  0.02102354  0.02103036  0.01978311
   0.01730279  0.01723639  0.01576029  0.0155317   0.01